dist:     trusty    # используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
sudo:     required

language: cpp       # на практике разницы между специфичным для C++ окружением
                    # и, скажем, python -- никакой. Но пусть будет cpp.

os:
    # будем прогонять CI и на Linux
    - linux

compiler:
    # ... и с помощью G++
    - g++
install:
    # скрипт настройки среды и установки зависимостей
    - source ./install-linux.sh

script:
    # скрипт сборки и тестирования проекта:
    - vera++ ./main.cpp
